mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking?characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 60000
      idle-timeout: 60000
      connection-init-sql: SELECT 1
server:
  error:
    include-message: always
logging:
  level:
    com.jip.booking.repository: DEBUG